"""empty message

Revision ID: 2c1c0480cbec
Revises: f3fa8404ef27
Create Date: 2020-06-24 13:06:42.035156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1c0480cbec'
down_revision = 'f3fa8404ef27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('limitnum')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('limitnum',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('day', sa.INTEGER(), nullable=False),
    sa.Column('meal', sa.INTEGER(), nullable=False),
    sa.Column('limit', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
