"""update datastr column in Ingredient table

Revision ID: 63ac30e42644
Revises: 2c1c0480cbec
Create Date: 2020-06-26 12:05:42.640136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63ac30e42644'
down_revision = '2c1c0480cbec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient', sa.Column('datastr', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient', 'datastr')
    # ### end Alembic commands ###
